language: scala
scala:
- 2.11.7
jdk:
- openjdk7
sudo: false
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "*[\[\]\(\)]*.properties" -type f -delete

